name: "Run a benchmark"

run-name: "Benchmark ${{ inputs.system }} on ${{ inputs.machine }} from ${{ inputs.repo }}@${{ inputs.branch }}"

on:
  workflow_dispatch:
    inputs:
      system:
        description: "System to benchmark (a directory name)"
        required: true
      machine:
        description: "EC2 instance type"
        default: "c6a.4xlarge"
      repo:
        description: "Repository to clone on the machine"
        default: "ClickHouse/ClickBench"
      branch:
        description: "Branch to clone"
        default: "main"
      timeout:
        description: "Time limit for benchmark.sh, seconds"
        default: "36000"

permissions:
  id-token: write  # To assume the federated IAM role.
  contents: read

jobs:
  launch:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/launch-benchmark
        with:
          system: ${{ inputs.system }}
          machine: ${{ inputs.machine }}
          repo: ${{ inputs.repo }}
          branch: ${{ inputs.branch }}
          timeout: ${{ inputs.timeout }}
          role-to-assume: ${{ vars.BENCHMARK_AWS_ROLE_ARN }}
          aws-region: ${{ vars.BENCHMARK_AWS_REGION }}
